gcp_project = "your-gcp-project-id"
gcp_service_account_key = "path/to/your/service-account-key.json"
region = "us-central1"
db_name = "your-database-name"
bucket_name = "your-bucket-name"
container_image = "gcr.io/your-project-id/your-image:latest"
service_name = "your-service-name"
