name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/php-app .

    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/php-app

    - name: Deploy to Cloud Run
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud run deploy php-app --image=gcr.io/${{ secrets.GCP_PROJECT }}/php-app --region=us-central1 --platform=managed
